# ios/Podfile

platform :ios, '15.0'  # Minimum iOS sürümü

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run 'flutter pub get' first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase ve Awesome Notifications
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # OneSignal framework (eğer kullanıyorsan)
  pod 'OneSignalXCFramework', '5.2.14'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Deployment target
      config.build_settings['IPHONES_DEPLOYMENT_TARGET'] = '15.0'

      # M1 / Simulator uyumu
      if ENV['SIMULATOR_ARCHS'] == 'arm64'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end

      # Swift ayarları
      config.build_settings['SWIFT_COMPILATION_MODE'] = 'incremental'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'

      # Bitcode kapalı
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # dSYM dosyaları
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'

      # GCC preprocessor
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PERMISSION_CAMERA=1']
    end
  end
end
